-- TCC Community v15: Official Groups, Events, RSVPs and Announcements
create table if not exists public.community_groups (id uuid primary key default gen_random_uuid(), name text not null check(char_length(trim(name)) between 2 and 120), description text, department_id uuid references public.departments(id) on delete set null, is_official boolean not null default true, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.community_group_members (group_id uuid references public.community_groups(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, joined_at timestamptz not null default now(), primary key(group_id,user_id));
create table if not exists public.community_events (id uuid primary key default gen_random_uuid(), title text not null check(char_length(trim(title)) between 2 and 160), description text, starts_at timestamptz not null, ends_at timestamptz, location text, department_id uuid references public.departments(id) on delete set null, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.community_event_rsvps (event_id uuid references public.community_events(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, status text not null default 'going' check(status in ('going','interested','not_going')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(event_id,user_id));
create table if not exists public.community_announcements (id uuid primary key default gen_random_uuid(), title text not null check(char_length(trim(title)) between 2 and 160), body text not null check(char_length(trim(body)) between 1 and 5000), department_id uuid references public.departments(id) on delete set null, created_by uuid not null references auth.users(id) on delete restrict, published boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists community_events_starts_idx on public.community_events(starts_at);
create index if not exists community_announcements_created_idx on public.community_announcements(created_at desc);
alter table public.community_groups enable row level security; alter table public.community_group_members enable row level security; alter table public.community_events enable row level security; alter table public.community_event_rsvps enable row level security; alter table public.community_announcements enable row level security;
drop policy if exists "groups active members read" on public.community_groups; create policy "groups active members read" on public.community_groups for select to authenticated using(exists(select 1 from public.member_access ma where ma.user_id=auth.uid() and ma.status='active') and (department_id is null or department_id=(select ma.department_id from public.member_access ma where ma.user_id=auth.uid() and ma.status='active')));
drop policy if exists "group members self" on public.community_group_members; create policy "group members self" on public.community_group_members for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and exists(select 1 from public.member_access ma where ma.user_id=auth.uid() and ma.status='active'));
drop policy if exists "events active members read" on public.community_events; create policy "events active members read" on public.community_events for select to authenticated using(exists(select 1 from public.member_access ma where ma.user_id=auth.uid() and ma.status='active') and (department_id is null or department_id=(select ma.department_id from public.member_access ma where ma.user_id=auth.uid() and ma.status='active')));
drop policy if exists "rsvps self" on public.community_event_rsvps; create policy "rsvps self" on public.community_event_rsvps for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and exists(select 1 from public.member_access ma where ma.user_id=auth.uid() and ma.status='active'));
drop policy if exists "announcements active members read" on public.community_announcements; create policy "announcements active members read" on public.community_announcements for select to authenticated using(published=true and exists(select 1 from public.member_access ma where ma.user_id=auth.uid() and ma.status='active') and (department_id is null or department_id=(select ma.department_id from public.member_access ma where ma.user_id=auth.uid() and ma.status='active')));
do $$ begin alter publication supabase_realtime add table public.community_events; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.community_announcements; exception when duplicate_object then null; end $$;
