-- TCC Community v17: Notification Center
-- Run after community_admin_content_v16.sql and all previous Community migrations.
--
-- IMPORTANT: community_engagement_migration.sql already creates
-- public.community_notifications with an older, incompatible schema
-- (no `link`/`metadata` columns, and a narrower `kind` check constraint).
-- Because that migration runs first, the `create table if not exists`
-- below is a no-op on any database that already ran it — so this file
-- must ALTER the existing table instead of assuming its own CREATE TABLE
-- actually took effect. Without this, every insert in api/community.js
-- that uses `link`/`metadata`, or a `kind` value outside the old
-- constraint's list (e.g. 'feed_comment', 'admin', 'community_access_approved'),
-- fails with a Postgres error at runtime.
create table if not exists public.community_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid null references auth.users(id) on delete set null,
  kind text not null check (kind in (
    'message','connection_request','connection_accepted',
    'group_message','event_reminder','event_update',
    'announcement','feed_comment','feed_like','admin'
  )),
  title text not null check (char_length(trim(title)) between 1 and 160),
  body text,
  link text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz null,
  created_at timestamptz not null default now()
);

-- Bring an already-existing (pre-v17) table up to the schema this feature needs.
alter table public.community_notifications add column if not exists link text;
alter table public.community_notifications add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.community_notifications alter column body drop not null;

-- Replace the kind check constraint with the union of every value actually
-- inserted anywhere in api/community.js (old and new code paths both still
-- run against this one table), plus the values reserved for future use by
-- this migration's own feature list.
alter table public.community_notifications drop constraint if exists community_notifications_kind_check;
alter table public.community_notifications add constraint community_notifications_kind_check check (kind in (
  'message','direct_message','connection_request','connection_accepted',
  'group_message','event_reminder','event_update','announcement',
  'feed_comment','feed_like','admin','system','community_access_approved'
));

create index if not exists community_notifications_user_created_idx
  on public.community_notifications(user_id, created_at desc);

create index if not exists community_notifications_unread_idx
  on public.community_notifications(user_id, read_at, created_at desc);

alter table public.community_notifications enable row level security;

drop policy if exists "notifications own select" on public.community_notifications;
create policy "notifications own select"
on public.community_notifications for select to authenticated
using (user_id = auth.uid());

drop policy if exists "notifications own update" on public.community_notifications;
create policy "notifications own update"
on public.community_notifications for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

do $$ begin
  alter publication supabase_realtime add table public.community_notifications;
exception when duplicate_object then null; end $$;

-- Event reminders are generated by the application/cron layer.
-- This migration intentionally does not create a database cron job.
