create extension if not exists pgcrypto;
create table if not exists subscribers(id uuid primary key default gen_random_uuid(),email text unique not null,created_at timestamptz default now());
create table if not exists sermons(id uuid primary key default gen_random_uuid(),title text not null,speaker text,date date,video_url text,description text,created_at timestamptz default now());
create table if not exists events(id uuid primary key default gen_random_uuid(),title text not null,date timestamptz not null,location text,description text,created_at timestamptz default now());
create table if not exists announcements(id uuid primary key default gen_random_uuid(),title text not null,body text not null,created_at timestamptz default now());
create table if not exists prayer_requests(id uuid primary key default gen_random_uuid(),name text,email text,subject text,message text not null,status text default 'new',created_at timestamptz default now());
create table if not exists visitors(id uuid primary key default gen_random_uuid(),name text not null,email text,phone text,message text,status text default 'new',created_at timestamptz default now());
create table if not exists giving_records(id uuid primary key default gen_random_uuid(),donor_name text,amount numeric(12,2) not null,currency text default 'NGN',reference text,status text default 'pending',created_at timestamptz default now());
create table if not exists church_settings(id integer primary key default 1,church_name text,email text,phone text,location text,service_times text,updated_at timestamptz default now());
alter table subscribers enable row level security;
alter table sermons enable row level security;
alter table events enable row level security;
alter table announcements enable row level security;
alter table prayer_requests enable row level security;
alter table visitors enable row level security;
alter table giving_records enable row level security;
alter table church_settings enable row level security;
create policy "public read sermons" on sermons for select using(true);
create policy "public read events" on events for select using(true);
create policy "public read announcements" on announcements for select using(true);
create policy "public insert subscribers" on subscribers for insert with check(true);
create policy "public insert prayer" on prayer_requests for insert with check(true);
create policy "public insert visitors" on visitors for insert with check(true);